menu:
  Home: /
  Archives: /archives
  About: /about

widgets: 
- search
- category
- tag
- twitter

excerpt_link:

github:
  username:  

twitter:
  username: 
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss: